### ISSUE TITLE
Query on reflected signals addition to the quasi-deterministic channel model

### ISSUE THREAD

**Issue by RahulSinghGulia** [hanyassasa87/ns3-802.11ad#10]
Hi,

My research has bought me to this NS-3 model. First of all, I would like to thank you for providing a very good start to the 802.11ad model in NS-3. 

I am working on the reflected signals from an AP in an indoor environment. And this paper "Enhancing the ns-3 IEEE 802.11ad Model Fidelity: Beam Codebooks, Multi-antenna Beamforming Training, and Quasi-deterministic mmWave Channel." says that the Q-D channel realization also generates reflected signals in an environment. I was trying to see the class/function in the 802.11ad NS-3 model that adds the reflection to the Q-D channel based on LOS/NLOS. 

I can see that the /NS-3/src/wifi/model/qd-propagation-engine.cc is responsible to generate all the related losses. But I could not find anything that was responsible to add the reflected signals too, as mentioned in the paper. Is there any other class file that does that?

Kindly let me know if I am looking at the wrong place, and point me in the right direction if possible. Looking forward to hearing back from you.

Thank you,
Rahul

**Comment by hanyassasa87** [comment]
The Q-D Realization software is a different piece of software that takes care of generating the mmWave channel. The ns-3 model only parses the Q-D traces and generates the corresponding channel gain. In the paper, we do not mention that ns-3 adds reflected signals as it is the responsibility of different software to do that.

Regards,
Hany
