### ISSUE TITLE
a consult for wigig-module working with nr-u

### ISSUE THREAD

**Issue by kicejade** [hanyassasa87/ns3-802.11ad#14]
Hi,

I am a student from Xiamen University, and I am currently working on a network simulation project.
I would like to combine the wigig module with the nr-u module, which is another ns-3 based module.
I was wondering if it is possible to integrate the wigig module into the ns-3 master branch alongside the nr-u module.
If so, I would greatly appreciate any advice or guidance you can provide on this matter.
Your input would be extremely valuable and helpful to me!

Best regards,

**Comment by nsrCodes** [comment]
were you ever able to make it work?
the nr-u module for ns3 does have an example of nr-u wigig interference, but the documentation suggests that it used a modified version of this module to do so.
https://gitlab.com/cttc-lena/nr-u/-/blob/master/examples/cttc-nr-wigig-interference.cc

**Comment by kitswas** [comment]
https://gitlab.com/cttc-lena/nr-u/-/issues/3#note_555770484
And a maintainer of the NR-U module says

> due to restrictions on the WiGig code we used in our paper, there are currently no working examples (even if some source code is under the examples/ directory, it will not be compiled).
