### ISSUE TITLE
scratch/evaluate_fst_mechanism.cc not working

### ISSUE THREAD

**Issue by rr999888tw** [hanyassasa87/ns3-802.11ad#7]
I'm playing with the script in /scratch, but some of them have errors.
This is one of the scripts I can't fix myself, so I turn to you for your kindness.

![image](https://user-images.githubusercontent.com/36822122/67909422-2bf46000-fb4d-11e9-928e-286ccc9a6fa8.png)

$ ./waf --run "scratch/evaluate_fst_mechanism --llt=10000 --dataRate=5Gbps"
Waf: Entering directory `/home/robinlin/Desktop/ns3-802.11ad/build'
Waf: Leaving directory `/home/robinlin/Desktop/ns3-802.11ad/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (0.589s)
assert failed. cond="uid <= m_information.size () && uid != 0", file=../src/core/model/type-id.cc, line=457
terminate called without an active exception
Command ['/home/robinlin/Desktop/ns3-802.11ad/build/scratch/evaluate_fst_mechanism', '--llt=10000', '--dataRate=5Gbps'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run <program> --command-template="gdb --args %s <args>").

**Comment by DouwesDekker** [comment]
Try to type (./waf configure) and (./waf build) before trying that scratch. You can see that command on README.md file on building the project. 
 
  On Thu, Oct 31, 2019 at 7:42 AM, rr999888tw<notifications@github.com> wrote:   
I'm playing with the script in /scratch, but some of them have errors.
This is one of the scripts I can't fix myself, so I turn to you for your kindness.



$ ./waf --run "scratch/evaluate_fst_mechanism --llt=10000 --dataRate=5Gbps"
Waf: Entering directory /home/robinlin/Desktop/ns3-802.11ad/build' Waf: Leaving directory /home/robinlin/Desktop/ns3-802.11ad/build'
Build commands will be stored in build/compile_commands.json
'build' finished successfully (0.589s)
assert failed. cond="uid <= m_information.size () && uid != 0", file=../src/core/model/type-id.cc, line=457
terminate called without an active exception
Command ['/home/robinlin/Desktop/ns3-802.11ad/build/scratch/evaluate_fst_mechanism', '--llt=10000', '--dataRate=5Gbps'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run --command-template="gdb --args %s ").

**Comment by rr999888tw** [comment]
> Try to type (./waf configure) and (./waf build) before trying that scratch. You can see that command on README.md file on building the project. On Thu, Oct 31, 2019 at 7:42 AM, rr999888tw<notifications@github.com> wrote: I'm playing with the script in /scratch, but some of them have errors. This is one of the scripts I can't fix myself, so I turn to you for your kindness. $ ./waf --run "scratch/evaluate_fst_mechanism --llt=10000 --dataRate=5Gbps" Waf: Entering directory /home/robinlin/Desktop/ns3-802.11ad/build' Waf: Leaving directory /home/robinlin/Desktop/ns3-802.11ad/build' Build commands will be stored in build/compile_commands.json 'build' finished successfully (0.589s) assert failed. cond="uid <= m_information.size () && uid != 0", file=../src/core/model/type-id.cc, line=457 terminate called without an active exception Command ['/home/robinlin/Desktop/ns3-802.11ad/build/scratch/evaluate_fst_mechanism', '--llt=10000', '--dataRate=5Gbps'] terminated with signal SIGIOT. Run it under a debugger to get more information (./waf --run --command-template="gdb --args %s "). — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

I know how to configure and build, and I can get other files in scratch/ to run without error.
I think the script may have some bugs

**Comment by hanyassasa87** [comment]
At the moment, the FST mechanism does not work as we have changed many things in MAC layer to support Q-D channel implementation.

**Comment by rr999888tw** [comment]
> At the moment, the FST mechanism does not work as we have changed many things in MAC layer to support Q-D channel implementation.

Hi, @hanyassasa87 !!
Thanks for replying to me.
Is there any way I can get the FST to work?
For instance, can I find the previous version?

**Comment by hanyassasa87** [comment]
@rr999888tw the first initial version has the FST working perfectly.
