### ISSUE TITLE
802.11ad examples

### ISSUE THREAD

**Issue by RahulSinghGulia** [hanyassasa87/ns3-802.11ad#9]
Hi,

I have been looking around this model for a while now. And I wanted to know if there are any examples of 802.11 ad.

I have found examples of 802.11p, 802.11e, and 802.11n. But I could not find anything that shows that 802.11ad was implemented here. I am sorry if I sound blunt because of the lack of my knowledge of this model. But I could not find anything on the 802.11ad model.

Any guidance would be appreciated.

Thank you,
Rahul

**Comment by hanyassasa87** [comment]
Hi @RahulSinghGulia ,

In the README file under the Tutorial Scripts section, I mention that all the examples are located inside the scratch folder.
https://github.com/wigig-tools/ns3-802.11ad/tree/master/scratch

**Comment by RahulSinghGulia** [comment]
Got it. Thank you.
